const ACTION_TYPE = {
    LOAD_NOTES: "LOAD_NOTES",
    DELETE_NOTES: "DELETE_ALL_NOTES",
    CREATE_NOTE: "CREATE_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    DELETE_NOTE: "DELETE_NOTE"
};

export default ACTION_TYPE;
