const ACTION_TYPE = {
    LOAD_NOTES: "LOAD_NOTES",
    DELETE_NOTES: "DELETE_ALL_NOTES",
    CREATE_NOTE: "CREATE_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
    OPEN_DIALOG: "OPEN_DIALOG",
    CLOSE_DIALOG: "CLOSE_DIALOG"
};

export default ACTION_TYPE;
